import { Arc, SiteConfig } from "./types";
import { STATIC_BODY } from "./staticBody";

/** Escape a JS string for use as a C# double-quoted literal. */
function cs(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

/** Format a number the way it should appear in C# source (no thousands sep). */
function num(n: number): string {
  if (!Number.isFinite(n)) return "0";
  return String(n);
}

function bool(b: boolean): string {
  return b ? "true" : "false";
}

function csDirection(d: Arc["direction"]): string {
  return d === "CW" ? "GantryDirection.Clockwise" : "GantryDirection.CounterClockwise";
}

function csAvoidSectors(sectors: Arc["avoidSectors"]): string {
  if (!sectors || sectors.length === 0) return "new double[0][]";
  const inner = sectors
    .map(([a, b]) => `new double[] { ${num(a)}, ${num(b)} }`)
    .join(", ");
  return `new double[][] { ${inner} }`;
}

/** Current UTC timestamp formatted like the templates: "YYYY-MM-DD HH:mm:ss UTC". */
function utcStamp(d = new Date()): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return (
    `${d.getUTCFullYear()}-${p(d.getUTCMonth() + 1)}-${p(d.getUTCDate())} ` +
    `${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())} UTC`
  );
}

function buildHeader(cfg: SiteConfig, stamp: string): string {
  return `//------------------------------------------------------------------------------
// AUTO-GENERATED ESAPI plug-in script  --  DO NOT EDIT THE GEOMETRY BY HAND.
// Generated by the ESAPI AutoPlan framework from site_templates.json.
// Site            : ${cfg.siteName}
// RapidPlan model : ${cfg.rpModelId}
// Generated (UTC) : ${stamp}
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. Improper
// scripting can corrupt treatment plans and/or the TPS. This script CREATES a
// DRAFT plan in a NEW course for offline review. It does not approve, schedule
// or deliver anything. A qualified medical physicist MUST review every plan,
// objective and dose distribution before any clinical use.
//
// Tested conceptually against the workflow in "Supplementary material 2"
// (ESAPI plug-in pattern). Target Eclipse/ESAPI version: 17.0.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Text;
using System.Windows;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using VMS.TPS.Common.Model.API;
using VMS.TPS.Common.Model.Types;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("AutoPlan ${cfg.siteKey}")]
[assembly: ESAPIScript(IsWriteable = true)]

namespace VMS.TPS
{
    public class Script
    {
        public Script() { }
`;
}

function buildTargetLevels(cfg: SiteConfig): string {
  if (cfg.targetLevels.length === 0) {
    return "        {\n            // (none - REQUIRES MAPPING)\n        };";
  }
  const lines = cfg.targetLevels
    .map((t) => `            { ${cs(t.structureId)}, new DoseValue(${num(t.dose)}, ${cs(t.unit)}) },`)
    .join("\n");
  return `        {\n${lines}\n        };`;
}

function buildStructureMatches(cfg: SiteConfig): string {
  if (cfg.structureMatches.length === 0) {
    return "        {\n            // (none - REQUIRES MAPPING)\n        };";
  }
  const lines = cfg.structureMatches
    .map((m) => `            { ${cs(m.patientId)}, ${cs(m.modelId)} },`)
    .join("\n");
  return `        {\n${lines}\n        };`;
}

function buildSuggested(cfg: SiteConfig): string {
  const n = cfg.suggestedMatches.length;
  const head =
    `        // ---- Suggested matches for this site (planner to complete if mapping required) ----\n` +
    `        // ${n} suggestion(s); uncomment & set the model structure IDs:`;
  if (n === 0) {
    return head + "\n            // (no suggestions)";
  }
  const lines = cfg.suggestedMatches
    .map((s) => `            // matches.Add(${cs(s)}, "<model structure id>");`)
    .join("\n");
  return head + "\n" + lines;
}

function buildArcs(cfg: SiteConfig): string {
  const lines = cfg.arcs
    .map(
      (a) =>
        `            new ArcSpec { Id = ${cs(a.id)}, CollimatorAngle = ${num(a.collimatorAngle)}, ` +
        `GantryStart = ${num(a.gantryStart)}, GantryStop = ${num(a.gantryStop)}, ` +
        `Direction = ${csDirection(a.direction)}, DoseRate = ${num(a.doseRate)}, ` +
        `X1 = ${num(a.x1)}, Y1 = ${num(a.y1)}, X2 = ${num(a.x2)}, Y2 = ${num(a.y2)}, ` +
        `AvoidSectors = ${csAvoidSectors(a.avoidSectors)} },`
    )
    .join("\n");
  return lines;
}

function buildSetupFields(cfg: SiteConfig): string {
  return cfg.setupFields
    .map(
      (s) =>
        `            new SetupSpec { Id = ${cs(s.id)}, Gantry = ${num(s.gantry)}, ` +
        `X1 = ${num(s.x1)}, Y1 = ${num(s.y1)}, X2 = ${num(s.x2)}, Y2 = ${num(s.y2)} },`
    )
    .join("\n");
}

function buildConfig(cfg: SiteConfig): string {
  return `
        // ===================== GENERATED CONFIGURATION (REVIEW ME) =====================
        // Every clinical parameter below was generated from site_templates.json.
        // Verify against your clinic's planning directive before running.

        private const string SITE_KEY   = ${cs(cfg.siteKey)};
        private const string SITE_NAME  = ${cs(cfg.siteName)};

        // ---- Machine / energy ----
        private const string MACHINE_ID = ${cs(cfg.machineId)};   // <-- MUST match your Linac
        private const string ENERGY     = ${cs(cfg.energy)};
        private const int    DOSE_RATE  = ${num(cfg.doseRate)};
        private const string TECHNIQUE  = ${cs(cfg.technique)};

        // ---- Prescription ----
        private const int    N_FRACTIONS    = ${num(cfg.nFractions)};
        private const double DOSE_PER_FX_GY = ${num(cfg.dosePerFxGy)};
        private const double TREAT_PCT      = ${num(cfg.treatPct)};   // 1.0 == 100%
        private const string RX_TARGET_ID   = ${cs(cfg.rxTargetId)};

        // ---- Algorithms (strings MUST match your Eclipse install) ----
        private const string OPT_ALGO = ${cs(cfg.optAlgo)};
        private const string DOSE_ALGO = ${cs(cfg.doseAlgo)};
        private const string DVH_ALGO = ${cs(cfg.dvhAlgo)};

        // ---- RapidPlan ----
        private const string RP_MODEL_ID = ${cs(cfg.rpModelId)};
        private const bool   REQUIRES_STRUCTURE_MAPPING = ${bool(cfg.requiresStructureMapping)};

        // ---- Course / plan identity ----
        private const string COURSE_ID_BASE = ${cs(cfg.courseIdBase)};
        private const string PLAN_ID_BASE   = ${cs(cfg.planIdBase)};
        private const string ISOCENTER_SOURCE = ${cs(cfg.isocenterSource)};

        // ---- NTO ----
        private const bool   NTO_AUTOMATIC = ${bool(cfg.nto.automatic)};
        private const double NTO_PRIORITY  = ${num(cfg.nto.priority)};
        private const double NTO_DIST_MM   = ${num(cfg.nto.distMm)};
        private const double NTO_START_PCT = ${num(cfg.nto.startPct)};
        private const double NTO_END_PCT   = ${num(cfg.nto.endPct)};
        private const double NTO_FALLOFF   = ${num(cfg.nto.falloff)};

        // ---- Safety gates ----
        private const bool REQUIRE_CONFIRMATION   = ${bool(cfg.gates.requireConfirmation)};
        private const bool STOP_AFTER_DVH_ESTIMATE = ${bool(cfg.gates.stopAfterDvh)};
        private const bool AUTO_OPTIMIZE          = ${bool(cfg.gates.autoOptimize)};
        private const bool CALC_DOSE_AFTER_OPT    = ${bool(cfg.gates.calcDoseAfterOpt)};
        private const bool ABORT_IF_COURSE_EXISTS = ${bool(cfg.gates.abortIfCourseExists)};
        private const bool WRITE_REPORT           = ${bool(cfg.gates.writeReport)};
        private const string REPORT_DIR           = ${cs(cfg.gates.reportDir)};

        // ---- DRR ----
        private const bool   DRR_ENABLED = ${bool(cfg.drr.enabled)};
        private const double DRR_WEIGHT  = ${num(cfg.drr.weight)};

        // ---- Target dose levels (RapidPlan) ----
        private static readonly Dictionary<string, DoseValue> TARGET_LEVELS =
            new Dictionary<string, DoseValue>()
${buildTargetLevels(cfg)}

        // ---- Structure matches: patient structure ID -> RapidPlan model structure ID ----
        private static readonly Dictionary<string, string> STRUCTURE_MATCHES =
            new Dictionary<string, string>()
${buildStructureMatches(cfg)}

${buildSuggested(cfg)}

        // ---- Arc geometry ----
        private class ArcSpec
        {
            public string Id; public double CollimatorAngle;
            public double GantryStart; public double GantryStop;
            public GantryDirection Direction; public double DoseRate;
            public double X1, Y1, X2, Y2; public double[][] AvoidSectors;
        }
        private static readonly List<ArcSpec> ARCS = new List<ArcSpec>()
        {
${buildArcs(cfg)}
        };

        // ---- Setup fields ----
        private class SetupSpec
        { public string Id; public double Gantry; public double X1, Y1, X2, Y2; }
        private static readonly List<SetupSpec> SETUP_FIELDS = new List<SetupSpec>()
        {
${buildSetupFields(cfg)}
        };
        // ===============================================================================

`;
}

/** Generate the full ESAPI C# plug-in source for a site configuration. */
export function generateScript(cfg: SiteConfig, stamp = utcStamp()): string {
  return buildHeader(cfg, stamp) + buildConfig(cfg) + STATIC_BODY;
}

/** Suggested file name for the generated script. */
export function scriptFileName(cfg: SiteConfig): string {
  const key = (cfg.siteKey || "Site").replace(/[^A-Za-z0-9_-]/g, "");
  return `AutoPlan_${key}.cs`;
}
